name: Publish to PyPI
on:
  push:
    tags:
    - v*

jobs:
    build:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
          python-version: [3.6, 3.7, 3.8]
      steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.lock
          pip install setuptools wheel twine
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py bdist_wheel
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*
